spring:
  profiles:
    active: rp
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    basename: i18n/messagesa
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
security:
  jwt:
    token:
      secret-key: 6142b3c6f0e34477a899597cbd8ec45a2a5bd162415e617c0a32495215b8bc2ea01a3285149f94ae0f8a
      expire-length: 604800000
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.xypsp.admin.domain.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
